stages:
  - build

before_script:
  - useradd -U -m blacknote
  - "chown -R blacknote:blacknote ."

.build-deb: &build-debain
  image: golang
  stage: build
  script:
    -  su blacknote -p -c "export GOPATH=$(pwd); export GOBIN=$GOPATH/bin; /usr/local/go/bin/go get && /usr/local/go/bin/go test && /usr/local/go/bin/go build blacknote.go"
  artifacts: &artifacts
    name: "BlackNote_Binary_${CI_BUILD_REF_NAME}"
    paths:
      - blacknote
      - templates
      - resources

build-commit-debian:
  <<: *build-debain
  artifacts:
    <<: *artifacts
    expire_in: 3d

build-tag-debian:
  <<: *build-debain
  only: 
    - tags
